apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\temp\kompose.exe convert -c
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\temp\kompose.exe convert -c
        kompose.version: 1.24.0 (7c629530)
      creationTimestamp: null
      labels:
        io.kompose.service: consumer
    spec:
      containers:
        - args:
            - python
            - consumer.py
            - -p
            - "5672"
            - -s
            - rabbitmq
          image: consumer
          name: consumer
          resources: {}
      restartPolicy: Always
status: {}
