apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\temp\kompose.exe convert -c
    kompose.version: 1.24.0 (7c629530)
  creationTimestamp: null
  labels:
    io.kompose.service: producer
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: producer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\temp\kompose.exe convert -c
        kompose.version: 1.24.0 (7c629530)
      creationTimestamp: null
      labels:
        io.kompose.service: producer
    spec:
      containers:
        - args:
            - python
            - producer.py
            - -p
            - "5672"
            - -s
            - rabbitmq
            - -m
            - Hello
            - -r
            - "30"
          image: producer
          name: producer
          resources: {}
      restartPolicy: Always
status: {}
